spring:
  datasource:
    url: jdbc:mysql://ecommercedb.c5vapug9qok4.ap-southeast-1.rds.amazonaws.com:3306/AuthService
    username: admin
    password: 12345678
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka