server:
  port: 8084
spring:
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MicroInventoryService
    username: admin
    password: 123456